### ISSUE TITLE
Local speech to text

### ISSUE THREAD

**Issue by maxime1992** [martin-opensky/whisper-assistant-vscode#4]
Hello, this looks really good but uploading voice data to the cloud is a big no for me at least.

I was thinking that maybe it'd be a good idea to offer the ability to use something like https://github.com/Vaibhavs10/insanely-fast-whisper so that it can remain 100% local :)

**Comment by martin-opensky** [comment]
Hey @maxime1992 
All transcriptions happen on the local machine - no upload of voice data to the cloud occurs.

I think it would be a good idea to use Insanely Fast Whisper for performance reasons but I haven't had time to look into it.  Currently this plugin is using Whisper locally: https://github.com/openai/whisper

**Comment by maxime1992** [comment]
Oh I see thanks, I never realised that openai actually open sourced anything :laughing:!

I saw openAI and just assumed it was running in the cloud. Thanks for the clarification. I'll definitely won't have time for this I'm afraid so feel free to discard the request as it's local already. Up to you really!
